package modelo;
// Generated 18 dic 2024, 8:31:15 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private Integer idEspacio;
	private String nombre;
	private String descripcion;
	private String tipo;
	private String categoria;
	private Double latitud;
	private Double longitud;
	private Set municipiosEspaciosNats = new HashSet(0);

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(String nombre, String descripcion, String tipo, String categoria, Double latitud,
			Double longitud, Set municipiosEspaciosNats) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.categoria = categoria;
		this.latitud = latitud;
		this.longitud = longitud;
		this.municipiosEspaciosNats = municipiosEspaciosNats;
	}
	
	public EspaciosNaturales(Integer idEspacio, String nombre, String descripcion, String tipo, String categoria,
			Double latitud, Double longitud) {
		this.idEspacio = idEspacio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.categoria = categoria;
		this.latitud = latitud;
		this.longitud = longitud;
}


	public Integer getIdEspacio() {
		return this.idEspacio;
	}

	public void setIdEspacio(Integer idEspacio) {
		this.idEspacio = idEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	public Set getMunicipiosEspaciosNats() {
		return this.municipiosEspaciosNats;
	}

	public void setMunicipiosEspaciosNats(Set municipiosEspaciosNats) {
		this.municipiosEspaciosNats = municipiosEspaciosNats;
	}

}
